name: haskell-web-app
version: 0.1.0.0
github: "githubuser/haskell-web-app"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/githubuser/haskell-web-app#readme>

default-extensions:
  - ApplicativeDo
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - PartialTypeSignatures
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - dotenv
  - envy
  - esqueleto
  - flow
  - monad-control
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - resource-pool
  - servant
  - servant-auth-server
  - servant-server
  - string-conversions
  - text
  - transformers
  - transformers-base
  - wai
  - warp

library:
  source-dirs: src

executables:
  haskell-web-app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-web-app

tests:
  haskell-web-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - haskell-web-app
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
